<Project>
  <PropertyGroup>
    <Version>1.5.2</Version>
    <InformationalVersion>1.5.2</InformationalVersion>
    <!-- Prevent the .NET 8 SDK from appending the git commit hash to the informational version -->
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
  </PropertyGroup>
</Project>
