<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\src\WallpaperTurbo.Core\WallpaperTurbo.Core.csproj" />
    <ProjectReference Include="..\..\src\WallpaperTurbo.Updater\WallpaperTurbo.Updater.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
